//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rozliczenia.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPokazWszystkieNaleznosci
    {
        public int IdKontraktu { get; set; }
        public string Usluga { get; set; }
        public System.DateTime OkresDataOd { get; set; }
        public System.DateTime OkresDataDo { get; set; }
        public decimal Kwota { get; set; }
        public decimal KwotaRozliczona { get; set; }
        public decimal DoZaplaty { get; set; }
        public int idPartiiNaleznosci { get; set; }
    }
}
