//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rozliczenia.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vOferty
    {
        public decimal CenaOferty { get; set; }
        public string Oferta { get; set; }
        public string KodOferty { get; set; }
        public int LiczbaOkresow { get; set; }
        public string NazwaPakietu { get; set; }
        public decimal Cena { get; set; }
    }
}
