//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rozliczenia.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPokazRozliczenieWplat
    {
        public int IdKontraktu { get; set; }
        public System.DateTime DataWpisu { get; set; }
        public decimal KwotaWplatyBankowej { get; set; }
        public decimal KwotaPartiiWplaty { get; set; }
        public string Usluga { get; set; }
        public decimal KwotaNaleznosci { get; set; }
        public int IdWplaty { get; set; }
    }
}
